Hw1 try2
vnebelunka/afina pull request #2
Opened 2021-09-21 21:30 UTC by vnebelunka

- После 1 попытки заменил на unique ptr.
-  добавил shift элемента в начало листа.

2021-09-25 08:29 UTC, vnebelunka commented on src/storage/SimpleLRU.cpp
> +    if(node == _lru_head.get()){ //tail
// head

2021-09-25 08:32 UTC, vnebelunka commented on src/storage/SimpleLRU.cpp
> +        // If there is a key: we will delete it, because we have to put node in head
Комментарий не актуален.

2021-09-25 12:31 UTC, xphoenix requested changes
```
Set: {
  if (in index) { 
    update_node(*it)
  }
}

Insert: {
    if (in index) {
      return update_node(it)
    }
    insert_new_node()
}

PutIfAbsent() {
    if (in index) {
      return false;
    }
    return insert_new_node()
}
```

2021-09-25 12:31 UTC, xphoenix commented on src/storage/SimpleLRU.h
> +    void shift(lru_node *node) ;
Состояние и методы лучше вместе не писать:
```
private:
   <methods>
   
private:
   <state>
```

2021-09-25 12:31 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +            Set(key, value);
Имея итератор не надо делать поиск 2ды

2021-09-25 12:31 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +        // If there is a key: we will delete it, because we have to put node in head
Допустим кэш размером 1Кб, а Я делаю ```Put``` с ```value .size() == 1GB```, почему весь кэш отчищается?

2021-09-25 12:31 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +        }
Где-то Я уже это видел...

2021-09-25 12:31 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +        tail_cut(key, value);
Размер ключа учитывается _дважды_

2021-09-25 12:31 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +        tail_cut(key, value);
ОБъяснение/assert почему голова не удалится

2021-09-27 10:15 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +            update(&it->second.get(), value);
а ```return```?

2021-09-27 10:36 UTC, merged